version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: docker build . -t "667251554135.dkr.ecr.us-east-1.amazonaws.com/test-image:${CIRCLE_WORKFLOW_ID}"